#!/usr/bin/env bash
#
# Deploy SSH Wrapper
# App:
#
KEY_PATH=/var/www/launchpad/
KEY_NAME=id_deploy

if [ -f /var/www/.fabric_hosted ] ; then
	KEY_PATH=/etc/fabric/keys
fi
echo "wrapper"
/usr/bin/env ssh -2 -C -o "StrictHostKeyChecking=no" -i "${KEY_PATH}/${KEY_NAME}" $1 $2

