<?php
/**
 * database.config.php
 * The database configuration file for shared DSPs
 *
 * Retrieves database credentials from the authentication system and caches them
 */
global $_dbName;

const AUTH_ENDPOINT = 'http://cerberus.fabric.dreamfactory.com/api/instance/credentials';

//	This file must be present to hit this block...
if ( file_exists( '/var/www/.fabric_hosted' ) )
{
	require_once dirname( __DIR__ ) . '/web/protected/components/HttpMethod.php';
	require_once dirname( __DIR__ ) . '/web/protected/components/Curl.php';

	$_host = isset( $_SERVER, $_SERVER['HTTP_HOST'] ) ? $_SERVER['HTTP_HOST'] : gethostname();

	if ( false === strpos( $_host, '.cloud.dreamfactory.com' ) )
	{
		throw new \CHttpException( 401, 'You are not authorized to access this system.' );
	}

	$_parts = explode( '.', $_host );
	$_dbName = $_dspName = $_parts[0];

	//	Check for db config from provisioning...
	$_privatePath = '/data/storage/' . $_dspName . '/.private';
	$_config = require( $_privatePath . '/database.config.php' );

	if ( !empty( $_config ) && is_array( $_config ) )
	{
		return $_config;
	}

	//	Otherwise, get the credentials from the auth server...
	$_response = \Curl::get( AUTH_ENDPOINT . '/' . $_dspName . '/database' );

	if ( !$_response || !is_object( $_response ) || false == $_response->success )
	{
		throw new RuntimeException( 'Cannot connect to authentication service:' . print_r( $_response, true ) );
	}

	$_dbCredentialsCache = $_response->details;

	//	Also create a config file for next time...
	$_date = date( 'c' );
	file_put_contents(
		$_privatePath . '/database.config.php',
		<<<PHP
<?php
/** generated by DSP @ {$_date} */
return array(
	'connectionString' => 'mysql:host=localhost;port=3306;dbname={$_dbName}',
	'username'         => '{$_dbUser}',
	'password'         => '{$_dbPassword}',
	'emulatePrepare'   => true,
	'charset'          => 'utf8',
);
PHP
	);

	$_dbName = $_dbCredentialsCache->db_name;
	$_dbUser = $_dbCredentialsCache->db_user;
	$_dbPassword = $_dbCredentialsCache->db_password;
}
else
{
	$_dbName = 'dreamfactory';
	$_dbUser = 'dsp_user';
	$_dbPassword = 'dsp_user';
}

return array(
	'connectionString' => 'mysql:host=localhost;port=3306;dbname=' . $_dbName,
	'username'         => $_dbUser,
	'password'         => $_dbPassword,
	'emulatePrepare'   => true,
	'charset'          => 'utf8',
);